version: "3.3"

services:
  api:
    image: e-taxi-micro:latest
    env_file: docker-compose.env
    environment:
      SERVICES: api/apiCallCenter.service.js,api/apiCustomer.service.js,api/apiDriver.service.js,common/socket.service.js
    depends_on:
      - helper_services
      - core_services
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"

  helper_services: 
    build:
      context: ../..
    image: e-taxi-micro:latest
    env_file: docker-compose.env
    environment:
      SERVICEDIR: services/common
      SERVICES: geo, sms, price
    deploy :
      replicas: 2
    

  core_services: 
    image: e-taxi-micro:latest
    env_file: docker-compose.env
    environment:
      SERVICEDIR: services/common
      SERVICES: customers, drivers, staffs, refreshTokens, address, address_customer
    deploy:
      replicas: 2
   
  
  # callcenter_services: 
  #   image: e-taxi-micro:latest
  #   restart: on-failure
  #   env_file: docker-compose.env
  #   environment:
  #     SERVICEDIR: services/callcenter
  #   depends_on:
  #     nats:
  #       condition: service_started
  #     redis:
  #       condition: service_started
  #     mongo:
  #       condition: service_started
  #     rabbitmq: 
  #       condition: service_healthy
  #       restart: true
  #     guard:
  #       condition: service_started

